### ISSUE TITLE
GOOGLEFINANCE function not working

### ISSUE THREAD

**Issue by Himan10** [Sampreeth1608/stockAutomation#4]
Hey pal, the function we've used so far in mostly all the scripts i.e., `=GOOGLEFINANCE("BOM:543396", "all", DATE(2021, 11, 22), 1, "DAILY")` doesn't seem to work anymore for this stock and others. 

I've tried every possible way to make it out but sadly it didn't. 
I have got an idea which revolves around 3 functions, which are as follows: 

1.  GET CURRENT DATE AND TIME
2.  GOOGLEFINANCE("BOM:543396", "price")
3.  GOOGLEFINANCE("BOM:543396", "volume")

what's your opinion on this @Sampreeth1608

**Comment by Sampreeth1608** [comment]
Yes bro go for this ... But use NSE stock quotes.. pls dnt use BSE

**Comment by Himan10** [comment]
Okay, let me try it and whatever the result I get, I will notify you according to that.

**Comment by Sampreeth1608** [comment]
K bro....
